services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      -  mongo  

  mongo:
    image: mongo
    ports: 
      - 27017:27017