services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi
    ports:
      - 80:80
    restart: "no"
    depends_on:
      -  mongo  

  mongo:
    image: mongo
    ports: 
      - 27017:27017
